# Generated by Django 3.1 on 2020-10-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_career', models.ImageField(blank=True, upload_to='products_images')),
                ('date', models.PositiveIntegerField(verbose_name='Год трудоустройства')),
                ('name_info', models.CharField(max_length=44, verbose_name='Имя организации')),
                ('date_info', models.TextField(blank=True, verbose_name='Каткое описание организации')),
            ],
        ),
        migrations.CreateModel(
            name='portfolio_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_project', models.ImageField(blank=True, upload_to='products_images')),
                ('name_project', models.CharField(max_length=44, unique=True, verbose_name='Название проекта')),
                ('discription_project', models.TextField(blank=True, verbose_name='Каткое описание')),
                ('platform', models.CharField(max_length=20, verbose_name='Название платформы')),
                ('img_platform', models.ImageField(blank=True, upload_to='products_images')),
            ],
        ),
    ]
