# Generated by Django 3.1 on 2020-10-14 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='career',
            new_name='career_path',
        ),
    ]
