# Generated by Django 3.1 on 2020-10-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20201014_0840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='career_path',
            old_name='date_info',
            new_name='discription_info',
        ),
    ]
