# Generated by Django 3.1 on 2020-10-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20201014_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_project',
            name='discription_project',
            field=models.CharField(blank=True, max_length=20, verbose_name='Каткое описание'),
        ),
        migrations.AlterField(
            model_name='portfolio_project',
            name='name_project',
            field=models.CharField(max_length=13, unique=True, verbose_name='Название проекта'),
        ),
    ]
