# Generated by Django 3.1 on 2020-10-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201016_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio_project',
            name='discription_project',
            field=models.CharField(blank=True, max_length=40, verbose_name='Каткое описание'),
        ),
    ]
